modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="stupidthings"
version="2.0.0"
displayName="Stupid Things – Nostalgia Edition"
description='''Adds a bunch of random, stupid items. Enjoy!'''
authors="Furgl"

[[dependencies.stupidthings]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.stupidthings]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
